services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    container_name: proxy
    volumes:
      - sockets:/sockets
    depends_on:
      api-1:
        condition: service_healthy
      api-2:
        condition: service_healthy
    ports:
      - "9999:9999"
    cpu_period: 100000
    cpu_quota: 5000 # 0.05 CPU (Proxy is very light with Splice)
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - rinha-network

  api-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: api-1
    command: ["--index", "/data/ivf_index.bin", "--mcc-risk", "/resources/mcc_risk.json", "--port", "8080"]
    environment:
      - API_SOCKET=/sockets/api1.sock
      - THRESHOLD=0.6
      - NPROBE=15
    volumes:
      - sockets:/sockets
    cpu_period: 100000
    cpu_quota: 47500 # 0.475 CPU
    deploy:
      resources:
        limits:
          memory: 150M
    healthcheck:
      test: ["CMD", "curl", "-sf", "--unix-socket", "/sockets/api1.sock", "http://localhost/ready"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    networks:
      - rinha-network

  api-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: api-2
    command: ["--index", "/data/ivf_index.bin", "--mcc-risk", "/resources/mcc_risk.json", "--port", "8080"]
    environment:
      - API_SOCKET=/sockets/api2.sock
      - THRESHOLD=0.6
      - NPROBE=15
    volumes:
      - sockets:/sockets
    cpu_period: 100000
    cpu_quota: 47500 # 0.475 CPU
    deploy:
      resources:
        limits:
          memory: 150M
    healthcheck:
      test: ["CMD", "curl", "-sf", "--unix-socket", "/sockets/api2.sock", "http://localhost/ready"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    networks:
      - rinha-network

volumes:
  sockets:
    driver: local

networks:
  rinha-network:
    driver: bridge
